### ISSUE TITLE
Delivery notifications should also be handled

### ISSUE THREAD

**Issue by subramanyamVemu** [ofa/django-bouncy#7]
Hi 

Right only the complaint and bounce notifications are supported

It will be good to handle delivery notifications as well, so that when we are doing a newsletter we can know how many have been delivered

(Though we still need the image for analytics to figure out whether the delivered one's are opened/unopened)

Bala

**Comment by subramanyamVemu** [comment]
Hi 

Can you have a look at 
https://github.com/subramanyamVemu/django-bouncy/commit/bb276b19a006f45628c90f422c42cf2955642206

Thanks
Bala

**Comment by subramanyamVemu** [comment]
Did you get a chance to look into the code

Thanks
Bala

**Comment by subramanyamVemu** [comment]
Please update the documentation that deliveries are handled as well

Thanks
Bala

**Comment by nickcatal** [comment]
I added it to the readme in 478394be3c011d2be37350122ba524a1315d0bfe

Additional documentation would be highly appreciated, if you want.
